import type { NextPage } from 'next'
import {useState} from 'react'
import Head from 'next/head'
import Feed from '../components/Feed'
import Footer from '../components/Footer'
import Header from '../components/Header'


interface FormData{
  title:String,
  desc:String
}
const Home: NextPage = () => {
  const [toggle,setToggle]=useState(false)
  const [todo,setTodo]=useState(false)
  const [list, setList]=useState<FormData>({
    title:'',
    desc:''
    
  })
  const handleTodo=async(data:FormData)=>{
    
    try{
      create(data)
    }catch(err){
      console.log(err)
    }
    
  
  }

  async function create(data:FormData){
    try{
      fetch('http://localhost:3000/api/create',{
        body:JSON.stringify(data),
        headers:{
          'Content-Type':'application/json'
        },
        method: 'POST'
      }).then(()=>setList({title:'',desc:''}))
    }catch(err){
      console.log(err)
    }
  }
  return (
    <div className='container relative mx-auto mt-0 md:w-3/4  lg:w-3/4 md:h-full'>
      <Head>
        <title>ToDo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header add={()=>setTodo(!todo)} clicked={()=>{setToggle(!toggle)}}/>
        {
          todo &&
          <div className="absolute top-12  left-1/5 rounded-md text-black z-10 p-10 bg-white shadow-lg w-46 md:left-2/4">
            
            <>
              <h2 className="uppercase text-orange-500 mb-4 text-center">Add a todo</h2>
              <form onSubmit={e=>{
                e.preventDefault()
                handleTodo(list)
                console.log(list)
                }} className="flex flex-col space-y-4">
                <input type='text' name='title' onChange={e=>{setList({...list,[e.target.name]:e.target.value})}} placeholder="Todo Title" className="border-2 text-sm w-46 h-8 rounded-md indent-2 outline-none"/>
                <textarea name="desc" onChange={e=>{setList({...list,[e.target.name]:e.target.value})}} className="border-2 border-black-300 h-36 text-xs outline-none"></textarea>
                <button type='submit' className="border bg-blue-400 py-1  w-2/5 rounded-md cursor-pointer">Add</button>
              </form>
            </>
          </div>
        }
        <Feed />
        <Footer/>
     
    </div>
  )
}

export default Home
